# Generated by Django 5.0.4 on 2024-05-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
