# Generated by Django 5.0.4 on 2024-05-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_order_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
