# Generated by Django 5.0.4 on 2024-05-03 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_delivery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="location",
        ),
        migrations.AddField(
            model_name="delivery",
            name="address",
            field=models.CharField(default="nepal", max_length=255),
        ),
        migrations.AddField(
            model_name="delivery",
            name="order",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="order.order"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
