# Generated by Django 5.0.4 on 2024-04-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="th.png", upload_to=""),
        ),
    ]
