# Generated by Django 5.0.4 on 2024-04-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(default=99),
        ),
    ]
