# Generated by Django 5.0.4 on 2024-04-30 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
